[profile.default]
solc = "0.8.25"
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
via_ir = true
runs = 2000
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]
