name: Foundry Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FOUNDRY_PROFILE: ci
  ETH_RPC_URL: "https://eth.llamarpc.com"

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # Clean cache step
      - name: Clean Cache
        run: |
          forge cache clean
          rm -rf ~/.cache/forge
          rm -rf cache/
          rm -rf out/

      # Cache dependencies
      - name: Cache Forge Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/forge
            lib/
          key: ${{ runner.os }}-forge-${{ hashFiles('**/foundry.toml') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-forge-

      - name: Install Dependencies
        run: |
          forge install
          forge build --sizes

      # Run tests with parallel jobs and timeout
      - name: Run Tests
        run: forge test -vvv 
        timeout-minutes: 10

      # Run coverage with retries
      - name: Run Coverage
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: forge coverage --report lcov